### ISSUE TITLE
已有项目中加入vue3-oop出错

### ISSUE THREAD

**Issue by zhengdiandian** [agileago/fe-template#1]
你好 我在已有的项目中引入了opp 但是注册路由时报了
![image](https://user-images.githubusercontent.com/31314288/163745555-92882017-d53a-442d-a354-4db7a08ed75a.png)
这个错误

**Comment by zhengdiandian** [comment]
搞定了

**Comment by agileago** [comment]
可以加群
![qq](https://user-images.githubusercontent.com/11799110/163750676-784add60-422d-47ad-bf0f-e9ba6adaacda.jpeg)
